### ISSUE TITLE
User management in server settings

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [ParadoxOrigins/otakudiscordtheme#47]
Make text readable, probably by giving it the same background as the other settings? Assigned Paradox because he made the settings design.

**Comment by PwaPois** [comment]
wat, im pretty sure saske did that, lemme aassign saske 👀

**Comment by PwaPois** [comment]
closed that shiet cuz rein is so much blind that he didn't noticed that im already working on it FacePalm
